# Generated by Django 4.0.3 on 2022-05-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
        migrations.CreateModel(
            name='DeckDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='anki.deck')),
            ],
        ),
    ]
