# Generated by Django 4.0.3 on 2022-05-21 17:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='deck',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stat',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stat',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_stat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='anki.deck'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_stat', to='anki.card'),
        ),
    ]
