# Generated by Django 4.0.3 on 2022-05-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0002_remove_deck_description_deckdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckdescription',
            old_name='deck',
            new_name='deck_ref',
        ),
    ]
