# Generated by Django 4.0.3 on 2022-07-04 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anki', '0004_rename_deck_ref_deckdescription_deck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together={('name', 'owner')},
        ),
    ]
