# Generated by Django 4.0.3 on 2022-05-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0003_rename_deck_deckdescription_deck_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckdescription',
            old_name='deck_ref',
            new_name='deck',
        ),
    ]
